---
ignore:
  - /wordlists/
only:
  - '*.rb'
  - '*.yml'
  - '*.txt'
  - Rakefile
  - '*.md'
  - '*.gemspec'
  - Gemfile
languages:
  english:
    wordlists:
      - dictionary.txt
  ruby:
    only:
      - README.md
