---
ignore:
  - '*.spellr_wordlists'
  - wordlists/*
only:
  - '*.rb'
  - '*.yml'
  - '*.txt'
  - Rakefile
  - '*.md'
  - '*.gemspec'
  - Gemfile
languages:
  english:
    wordlists:
      - dictionary.txt
  ruby:
    only:
      - README.md
  lorem:
    only:
      - spec/*
      - .spellr.yml
